name: cicd

on:
    push:
        branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: azure/login@v1
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Upload to blob storage
      uses: azure/CLI@v1
      with:
        inlineScript: |
            az storage blob upload-batch --account-name taniastorageaccount --account-key ${{ secrets.AZURE_STORAGE_KEY }} --auth-mode key --overwrite -d 'webdata' -s .
   # - name: Purge CDN endpoint
   #   uses: azure/CLI@v1
   #   with:
   #     inlineScript: |
    #       az cdn endpoint purge --content-paths  "/*" --profile-name "StaticSiteHostingProject" --name "staticsiteamc" --resource-group "StaticSiteHostingProjectRG"
  # Azure logout
    - name: logout
      run: |
            az logout
      if: always()
